 # yaml-language-server: $schema=https://416c-171-246-97-52.ngrok-free.app/schema.json
   pull_request_rules:
     - name: test_xss
       conditions:
         - base=main
       actions:
         comment:
           message: test
